// apps/next-app/src/app/views/quote-view/quote-view.tsx
import { QuoteService } from "@/app/services/quote-service";
import React from "react";
import './quote-view.css';

export default async function QuoteView() {
  const quote = await QuoteService.getQuote();

  return (
    <>
      {!quote && <div>Loading quote...</div>}
      {!!quote && <div className="quote">{quote}</div>}
    </>
  );
}

// apps/angular-app/src/app/views/quote-view/quote-view.component.ts
import { AfterViewInit, Component } from '@angular/core';
import { Quote } from '../../models/quote';
import { QuotesService } from '../../services/quotes.service';

@Component({
  selector: 'app-quote-view',
  templateUrl: './quote-view.component.html',
  styleUrl: './quote-view.component.scss'
})
export class QuoteViewComponent implements AfterViewInit {
  public quote?: string;

  public constructor(private service: QuotesService) { }

  public ngAfterViewInit(): void {
    this.service.getQuote()
      .then((quote) => this.quote = quote);
  }
}

<div *ngIf="!quote">Loading quote...</div>
<div *ngIf="!!quote" class="quote">{{quote}}</div>
